services:
  qarrange:
    build: .
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: /run/secrets/openai_api_key
    secrets:
      - openai_api_key

secrets:
  openai_api_key:
    file: ./openai_api_key.secret